import React from 'react'

export default function EXERCISE06() {
    return (
        <div className='w-[500px] h-[200px] overflow-auto'>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Inventore nam temporibus corporis. Aspernatur perferendis iusto vero. Ea omnis nesciunt fugit consectetur delectus, magnam ipsam beatae distinctio placeat rem quod aliquam.
            Accusantium similique ab animi minus impedit labore veniam quod ipsa voluptates illum exercitationem eos temporibus modi totam, odio, distinctio doloribus fugit quidem libero laboriosam sint porro reprehenderit magni. Incidunt, adipisci?
            Harum quaerat, nemo dignissimos ipsa reprehenderit incidunt non deserunt. Quos molestiae, sed minus tenetur alias voluptatum tempore accusamus voluptate. Incidunt mollitia commodi cumque architecto, impedit modi autem consequuntur ipsam repudiandae.
            Cupiditate nam ea atque placeat aliquam rerum nulla. Nostrum sit minus praesentium ducimus natus maiores tenetur esse dolorem. Consequuntur ipsa obcaecati voluptate corrupti beatae magni minus. Tempora ad perspiciatis nam.
            Ipsum beatae adipisci, dignissimos quia omnis nobis vero nemo doloremque, enim nihil minima cumque nisi eaque quis labore velit praesentium numquam repellendus sequi magni cum consectetur! Reprehenderit excepturi ipsam ad.
            Minima totam autem nesciunt placeat saepe nostrum, perspiciatis rerum numquam minus deleniti vitae officiis officia cumque incidunt ipsum iure ad unde dignissimos, praesentium neque eaque atque aliquid reiciendis eligendi. Voluptates?
            Quidem nihil, labore iure tempora quasi ducimus suscipit excepturi culpa officiis fugiat autem totam aliquam a delectus, ad dolor iusto fuga nisi veritatis quos voluptatibus eligendi similique? Reiciendis, suscipit cupiditate.
            Fuga illo nisi culpa adipisci voluptatibus sed, ea eos ullam delectus quae corrupti animi placeat veritatis iste dignissimos quis non voluptates suscipit eum maxime expedita ut, dolores accusamus! Voluptatum, consectetur.
            Dolorem ipsum tempore repellendus sequi, a blanditiis odio reprehenderit soluta ratione quibusdam recusandae iusto quidem doloribus eaque velit. Placeat maiores eos sunt dolor ipsa aut quos optio laboriosam, sit voluptates.
            Explicabo, necessitatibus labore. Quis neque qui inventore debitis, eum perspiciatis dolor nesciunt voluptate sequi officiis omnis dignissimos recusandae quidem suscipit doloribus quo soluta veritatis nisi necessitatibus fugiat sunt! Odit, accusantium!
            Voluptates facere eum iste officia aspernatur et cum aliquid consectetur saepe temporibus odit, eius itaque tempore ratione quis laudantium doloremque consequuntur qui distinctio veniam fuga voluptate cupiditate quaerat minus. Corporis?
            Minus quia voluptatibus atque ea. Possimus natus nam ratione nisi. Consequatur omnis neque praesentium tempora itaque veritatis. Ex laboriosam quos, optio iste esse impedit est dolores, minus tempore cum quisquam.
            Reiciendis modi saepe sed officiis, obcaecati facere. Eligendi iste eius quibusdam voluptatibus architecto qui illum cumque veritatis temporibus expedita sapiente, sequi maiores rem illo dolorem animi? Sit consequuntur maxime aut.
            Obcaecati, accusantium dicta neque quae perferendis inventore nesciunt reprehenderit minima vero reiciendis impedit optio numquam, iure sit laboriosam consequatur quasi doloremque? Commodi nihil excepturi voluptatibus, odit atque et adipisci cumque.
            Aliquam reiciendis repellendus molestias. Porro, voluptates est nihil tempora, aliquam officia repellendus tenetur aliquid excepturi natus cumque dolorem vero debitis perspiciatis quo dolor eum? Blanditiis officia iusto id non a?
            Quisquam nulla ipsum labore et enim qui molestias autem voluptatum, dolore optio a excepturi vitae accusamus itaque? Repellat magni laboriosam rem culpa, minus dignissimos maiores possimus nisi dolorem, ipsum fuga?
            Nemo, cum soluta similique beatae eos natus nam pariatur temporibus ipsa quisquam deserunt ad nesciunt numquam iusto quam porro quasi vero, sed quo. Pariatur ut sunt veritatis et itaque accusamus!
            Optio et laboriosam fuga sit consequatur! Iure blanditiis error rem ducimus ad officiis vitae, quaerat eos animi ullam quia corporis magnam assumenda. Soluta repellat quod nam asperiores tenetur fuga? Nobis!
            Ipsum ex laboriosam, autem nesciunt, ut, rerum maxime est optio maiores dolores tempora placeat veritatis debitis quibusdam eius tenetur provident velit. Magnam explicabo molestias harum iusto quo accusamus nisi laudantium.
            Expedita libero esse corrupti dolorum est dolor ex odit autem maxime repellendus quod ipsam, minima quae quas veniam adipisci quaerat? Blanditiis facere veritatis ipsam et architecto. Temporibus voluptates vero repellendus.
            Officia quis eaque enim eius iusto laboriosam deleniti facilis perspiciatis porro obcaecati. Ut quis hic officia harum repellendus, iusto dignissimos quasi. Dolorum, dolore quidem cumque alias laudantium excepturi necessitatibus ipsam.
            Nisi quam necessitatibus, nostrum aliquam adipisci illum corrupti! Consequuntur dolor ex, neque dolores ipsam eligendi in deleniti eius distinctio sequi culpa, deserunt hic quam dolorem assumenda! Aperiam quidem expedita sapiente?
            Rem deserunt libero ipsum vel inventore est porro iusto impedit adipisci eligendi dolores, saepe hic asperiores ex atque minima quos obcaecati aliquid harum sapiente reprehenderit? Labore ab nobis temporibus consectetur.
            Doloremque minima numquam architecto perspiciatis totam iusto dolorem quasi blanditiis sed provident facere eum vitae unde corrupti corporis quaerat placeat suscipit veniam quisquam, tempora possimus laudantium! Aperiam, dignissimos. Quo, deserunt?
            Totam id autem, rem ipsa adipisci nobis iste repellendus sit, dicta eaque quibusdam laborum perspiciatis facilis distinctio in ducimus. Similique, laborum? Doloremque velit hic repellendus dolorem commodi rerum accusantium inventore.
            Quo inventore quas eum voluptatem facere illo deserunt, optio nam explicabo pariatur quae doloremque et, perferendis eos, ipsum amet corrupti molestias reprehenderit veritatis impedit voluptate quibusdam. Exercitationem sit incidunt qui!
            Ut iste voluptatibus molestias, officia aspernatur minus delectus enim. Necessitatibus, autem? Omnis, provident expedita ab incidunt dignissimos reiciendis et deleniti voluptatibus enim consequatur, minima animi! Tempore velit alias quasi quod?
            Mollitia architecto est magni vero, excepturi saepe totam nostrum ullam sunt vitae recusandae enim odit consequatur ab earum ea? Omnis neque non, magnam doloribus illum distinctio provident sint ab rem?
            Rem, reiciendis laudantium earum veniam repellat quaerat eaque alias iste unde sunt vero tenetur dolorem? Nam velit molestiae magni consequatur necessitatibus repellendus vitae distinctio mollitia modi ipsam, explicabo fugiat nulla.
            Rerum voluptas officia dolorum alias numquam laudantium. Doloribus, voluptatum! Ipsum delectus mollitia id quo magnam saepe quod tempore alias libero, quia fugiat nisi aliquid exercitationem deserunt facere consequuntur odio consectetur.
            Eligendi mollitia tempore labore officia deserunt distinctio sint nemo, dignissimos unde fuga repudiandae veritatis sit, suscipit ad ducimus illo? Harum sit repellat nostrum aut et iure totam consequuntur odio similique?
            Facilis atque, deserunt iure vel quidem at. Earum recusandae fugiat neque sunt, rerum temporibus deleniti dolore quo, odio laborum reiciendis cumque expedita, libero aut voluptates exercitationem ratione quaerat commodi minima?
            Officia magnam impedit dolorum distinctio? Fugit similique ab dolores nisi veritatis quod, facilis, quidem iure neque architecto perferendis aliquam distinctio provident facere at aliquid molestias labore vitae repellendus inventore. Qui.
            Facilis optio laudantium voluptatibus animi porro vel assumenda, laboriosam cum quisquam quos laborum quae eos, eligendi libero. Aut mollitia qui ex in commodi laboriosam corrupti. Accusantium unde illum accusamus magni.
            Debitis cum, dolore qui rem perferendis corrupti, ut blanditiis tempore impedit dicta earum iste consequatur sunt! Vero deleniti ipsam sequi accusantium, reprehenderit, quia blanditiis, at totam molestias odit dolorem incidunt?
            Dolor, praesentium ex, perspiciatis magnam tenetur ipsa iure aspernatur aliquam officia ut eaque necessitatibus animi tempore. Ab, maxime? Odio eveniet quae beatae maxime expedita et totam recusandae illo, assumenda fugit.
            Tempore expedita, provident ratione commodi obcaecati cupiditate natus. Nisi quia expedita quod nobis voluptatum, obcaecati magnam numquam laboriosam, impedit voluptatibus animi esse nemo corrupti placeat architecto, sequi aut? Sint, quaerat.
            Repudiandae iusto dicta a sint consequatur, adipisci omnis enim ipsa, rem, accusantium quos ipsum aperiam dolorum facere unde expedita placeat vel? Commodi amet praesentium odio sequi blanditiis iusto quidem nesciunt.
            Mollitia modi quam at dolor, a fuga fugiat harum, nobis dolorem veniam vero fugit corrupti cupiditate quos minus quo id deserunt aliquid ex atque, reprehenderit aspernatur similique soluta? Itaque, repellendus.
            Similique minima sed excepturi doloribus fugit quod ut molestias, in quisquam explicabo expedita enim maxime repellat eum aspernatur numquam adipisci nesciunt odit cupiditate velit. Numquam alias veritatis delectus eum nemo.
            Reiciendis, aliquid perferendis. Totam aut ex enim architecto commodi in officiis pariatur, ut laudantium dolores necessitatibus repellat facere quae quam ipsa alias? Explicabo, dolorum eum fuga expedita quae cum sapiente!
            Soluta hic ut quod! Esse, facere at. Similique asperiores, laboriosam pariatur quam est numquam vitae qui culpa rem beatae dignissimos. Quod vel vero porro nam iusto aspernatur odit blanditiis nobis!
            A, voluptatibus quisquam esse rerum maxime voluptatum magni placeat! Assumenda, similique odio. Cumque, ex vero impedit mollitia labore maxime culpa, exercitationem enim animi sunt rerum harum id, blanditiis quas fugiat!
            Qui unde neque ad, sapiente molestiae omnis, accusamus minima accusantium cupiditate nulla delectus veniam distinctio, facilis beatae repellat rem mollitia amet quasi aut? Eum ratione nam nemo itaque id? Repudiandae.
            Suscipit obcaecati sequi ea dolore cupiditate quasi unde voluptate molestias id esse, a culpa! Illo illum beatae obcaecati facere, ipsum, sunt nostrum excepturi totam incidunt sit ducimus quidem porro quae!
            Labore ipsam expedita eaque sint ad consectetur illo, voluptatem, vero dolore, corporis earum ullam! Aperiam aliquam minima dolorum vero veritatis enim similique temporibus, commodi deserunt nulla debitis laborum non aut?
            Architecto nisi quo aliquam esse voluptatibus nam cumque beatae repellendus minus deserunt quos necessitatibus quaerat atque quibusdam, similique est aspernatur veritatis velit eos voluptatum sequi nihil. Unde beatae nobis pariatur.
            Tempore doloremque eaque doloribus magni odio alias, vel quibusdam accusamus quidem porro cumque quia rerum amet voluptatem aperiam officia corporis. Quaerat nihil consectetur ratione nulla assumenda tenetur soluta mollitia repudiandae.
            Quibusdam sapiente perspiciatis molestias itaque, eveniet ipsum veritatis eligendi dicta sequi magnam. Illum vitae quisquam dolorem possimus quidem sint perspiciatis aspernatur distinctio odio iusto! Saepe necessitatibus quasi exercitationem minima mollitia?
            Aliquam rem illo commodi velit voluptatibus quam voluptatum quibusdam quis eligendi neque quas ipsa quaerat fugit, odit magnam eaque ratione repellat repellendus atque delectus ullam quia enim nostrum veniam! Voluptates.</div>
    );
}
